apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa-app
spec:
  selector:
    matchLabels:
      app: go-hpa-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa-app
    spec:
      containers:
      - name: go-hpa
        image: willlino/go-hpa:latest

        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
        